theme = "onedark"
[editor]
line-number = "relative"
mouse = true
idle-timeout = 0
auto-pairs = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true
