# theme = "onedark"
theme = "spacebones_light"
[editor]
line-number = "relative"
mouse = true
idle-timeout = 0

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.search]
smart-case = false

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "┊" # Some characters that work well: "▏", "┆", "┊", "⸽", "╎"
skip-levels = 1

[editor.soft-wrap]
enable = true

[keys.normal.space.space]
c = ":pipe sc -r -p 'complete this code'"
t = ":pipe sc -r -p 'write tests for this code'"
r = ":pipe sc -r -p 'refactor this code with a focus on clarity and concision'"
